---
- name: Copy roundcube config
  template:
    src: config.inc.php
    dest: '{{ roundcube_unarchive_dir }}/config/config.inc.php'
    owner: '{{ roundcube_user }}'
    group: '{{ roundcube_group }}'
    mode: '0400'
